# Generated by Django 5.2.4 on 2025-07-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop_api', '0003_selecredpruduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelecredPruduct',
            new_name='SelectedPruduct',
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
