# Generated by Django 5.2.4 on 2025-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop_api', '0004_rename_selecredpruduct_selectedpruduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedpruduct',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
