# Generated by Django 5.2.4 on 2025-07-26 17:25

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop_api', '0005_selectedpruduct_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRegistraion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('time_update', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(to='app_shop_api.selectedpruduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
