# Generated by Django 5.2.4 on 2025-07-27 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop_api', '0006_finalregistraion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalregistraion',
            name='products',
        ),
        migrations.AddField(
            model_name='finalregistraion',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shop_api.selectedpruduct'),
        ),
    ]
