# Generated by Django 5.2.4 on 2025-07-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop_api', '0007_remove_finalregistraion_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalregistraion',
            old_name='products',
            new_name='product',
        ),
    ]
