# Generated by Django 5.2.4 on 2025-07-27 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop_api', '0008_rename_products_finalregistraion_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalregistraion',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shop_api.product'),
        ),
    ]
