# Generated by Django 5.2.4 on 2025-07-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop_api', '0009_alter_finalregistraion_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
