# Generated by Django 5.2.4 on 2025-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop_api', '0012_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalregistraion',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.FileField(null=True, upload_to='./media/shoponline'),
        ),
    ]
